inherit_gem:
  main_branch_shared_rubocop_config: config/rubocop.yml

Metrics/MethodLength:
  Exclude:
    - "spec/spec_helper.rb"
    - "spec/**/*_spec.rb"

Metrics/AbcSize:
  Exclude:
    - "spec/spec_helper.rb"
    - "spec/**/*_spec.rb"

AllCops:
  TargetRubyVersion: 3.2
